export const homeObjOne = {
    id: 'chairman',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Message From Chairman',
    headline: 'Learn how to build',
    description: 'a React website using styled components and React smooth scroll. The website is fully responsive and we will be using React Hooks and React Router for this project. ',
    buttonLabel: 'Read More',
    imgStart: 'true',
    img: require('../../images/DSC_1961.JPG'),
    alt:'Student',
    dark: true,
    primary: false,
    darkText: false,
};

export const homeObjTwo = {
    id: 'former chairman',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Message From Former Chairman',
    headLine: 'Learn how to build',
    description: 'a React website using styled components and React smooth scroll. The website is fully responsive and we will be using React Hooks and React Router for this project. ',
    buttonLabel: 'Read More',
    imgStart: 'false',
    img: require('../../images/svg-1.svg'),
    alt:'student',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'chairman',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Message From Chairman',
    headLine: 'Learn how to build',
    description: 'a React website using styled components and React smooth scroll. The website is fully responsive and we will be using React Hooks and React Router for this project. ',
    buttonLabel: 'Read More',
    imgStart: 'true',
    img: require('../../images/svg-1.svg'),
    alt:'student',
    dark: true,
    primary: false,
    darkText: false,
};